### PR TITLE
Closed source software.

### PR DESCRIPTION
**Pull request by chairclr**
Closed source software.

### CODE REVIEW

**Review by punchready — APPROVED** [review]
LGTM

**Comment by chairclr** [comment]
LGTM

**Review by steviegt6 — APPROVED** [review]
LGTM

**Review by chairclr — COMMENTED** [review]
LGTM

**Comment by steviegt6** [comment]
LGTM, @hakusaro can we get a review?

**Comment by chairclr** [comment]
@yayakame can we get a review?

**Comment by yayakame** [comment]
LGTM

**Review by punchready — APPROVED** [review]
LGTM. @ZekusV can we get this merged?

**Comment by steviegt6** [comment]
Repository owner locked and limited conversation to collaborators yesterday

**Comment by steviegt6** [comment]
Repository owner unlocked this conversation yesterday

**Pull request closed without merging**
